theme: jekyll-theme-minimal
title: Welcome to the homepage of VirtualVale!
description: Feel free to bookmark this to keep an eye on my project updates!<p>Click <a href="#chapter4">here</a> to read chapter 4.</p><p>or <a href="#chapter4">projects</a></p>

