theme: jekyll-theme-minimal
title: Welcome to the homepage of VirtualVale!
description: ![Me](https://profile-images.xing.com/images/1f7e82c05504485a6932885c3b2afede-1/valentin-spannagl.1024x1024.jpg)Feel free to bookmark this to keep an eye on my project updates!<p>Click <a href="#chapter4">here</a> to read chapter 4.</p><p>or <a href="#chapter4">projects</a></p>

