theme: jekyll-theme-minimal
title: Valentin Spannagl
description: <a href="#biografy">Biografy</a><p><a href="#interests">Interests</a></p><p><a href="#projects">Projects</a></p><p><a href="https://www.xing.com/profile/Valentin_Spannagl">Xing</a></p><p><a href="https://de.linkedin.com/in/valentin-spannagl-a748991b5">LinkedIn</a></p>


